# Generated by Django 3.2.5 on 2021-07-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['-pk']},
        ),
    ]
