# Generated by Django 3.2.5 on 2021-07-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_alter_neighborhood_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='logo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
